name: Pre-Release

on:
  workflow_run:
    workflows: ["CI"]
    
    types: [completed]
    branches: [staging]


jobs:
  release:
    runs-on: ubuntu-latest
    environment: tests
    container:
      image: lukassgx/epi-docker:tek1-extended

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      issues: write

    steps:
      - uses: googleapis/release-please-action@v4
        id: pre-release
        with:
          target-branch: staging
          config-file: release-config.json
          manifest-file: .release-manifest.json

      - uses: actions/checkout@v6
        if: ${{ steps.pre-release.outputs.release_created }}
        with:
          fetch-depth: 0
          ref: staging

      - name: Build
        if: ${{ steps.pre-release.outputs.release_created }}
        run: |
          make

      - name: Upload to GitHub Release
        if: ${{ steps.pre-release.outputs.release_created }}
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          git config --global --add safe.directory /__w/C_zsh/C_zsh
          gh release upload ${{ steps.pre-release.outputs.tag_name }} 42sh